//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace co5027_1626739_assignment.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public string productDesc { get; set; }
        public string productPrice { get; set; }
        public Nullable<int> productStock { get; set; }
    }
}
